const translations = {
  en: {
      home: "Home",
      about: "About Us",
      services: "Services",
      destinations: "Destinations",
      reviews: "Reviews",
      gallery: "Gallery",
      contact: "Contact Us",
      booking: "Booking",
      login: "Login",
      who_we_are: "Who We Are",
      who_description: "At DiscoverJordan, we offer unforgettable travel experiences that showcase Jordan’s rich history, stunning landscapes, and warm hospitality. From Petra to the Dead Sea, we ensure each journey is memorable.",
      vision: "Our Vision",
      vision_description: "To be the leading travel platform in Jordan, providing immersive and authentic experiences that connect travelers with our local culture.",
      mission: "Our Mission",
      mission_description: "We curate personalized travel experiences for all types of travelers. Our focus is on sustainability, supporting local communities, and providing a seamless travel experience.",
      why_choose: "Why Choose DiscoverJordan?",
      why_description: "Choose DiscoverJordan for expert-guided tours, exclusive access to hidden gems, and authentic cultural experiences. With our easy and secure booking, your journey will be smooth from start to finish.",
      footer: "© 2025 DiscoverJordan | All rights reserved.",
      page_title_home: " Booking Now ",
      page_title_about: "About Us ",
      full_name: "Full Name:",
      email: "Email:",
      phone: "Phone Number:",
      full_name_placeholder: "Enter your name",
      email_placeholder: "Enter your email",
      phone_placeholder: "Enter your phone number",
      submit_booking: "Submit Booking",
      contact_title: "Contact Us",
      contact_description: "We'd love to hear from you. Please fill out the form below to get in touch with us.",
      name_label: "Your Name:",
      email_label: "Your Email:",
      message_label: "Your Message:",
      submit_button: "Send Message",
      contact_title: "Contact Us",
      contact_description: "We'd love to hear from you! Please reach out with any questions or comments.",
      get_in_touch: "Get In Touch",
      full_name_placeholder: "Enter your name",
      email_placeholder: "Enter your email",
      message_label: "Your Message",
      submit_button: "Send Message",
      our_address: "Our Address",
      follow_us: "Follow Us",
      address: "Amman, Jordan",
      explore:"Discover the most beautiful destinations in Jordan with our unique travel services! We help you design your perfect trip with ease",
      discover: "Discover breathtaking places and plan your next adventure!",
      topDestinations: "Top Destinations",
      petraDescription: "The ancient city of Petra, one of the Seven Wonders of the World.",
      wadiRumDescription: "Experience the stunning desert landscape and adventure activities.",
      deadSeaDescription: "Float effortlessly in the world's saltiest body of water.",
      explore_now: "Explore Destinations Now",
      request_services: "Request Our Services",
      what_visitors_say: "What Our Visitors Say",
      read_experiences: "Read the experiences of travelers who explored Jordan with us.",
      review_1: '"Amazing experience! Petra and Wadi Rum were breathtaking. Highly recommend!"',
      review_2: '"Great guides, smooth booking, and unforgettable adventures. Thank you!"',
      review_3: '"Loved the local hospitality and beautiful landscapes. Will visit again!"',
      leave_review: "Leave a Review",
      submit_review: "Submit",
      services_title: "Our Travel Services",
      services_intro: "Explore the wide range of services we offer for your perfect trip to Jordan.",
      tourist_tours: "Tourist Tours",
      tourist_tours_desc: "Discover the main attractions like Petra, Dead Sea, Wadi Rum, and more.",
      historical_tours: "Historical & Cultural Tours",
      historical_tours_desc: "Experience the rich history of Jordan with our cultural tours.",
      accommodation: "Accommodation Services",
      accommodation_desc: "Find the best hotels or apartments near major attractions.",
      transportation: "Transportation Services",
      transportation_desc: "Rent cars or book private transport to travel between attractions.",
      private_tours: "Private Tours",
      private_tours_desc: "Custom tours tailored to your interests and preferences.",
      restaurants: "Restaurants",
      restaurants_desc: "Discover Jordan's best dining spots, offering traditional and international cuisines.",
      tourist_tours: "Tourist Tours",
      historical_tours: "Historical & Cultural Tours",
      accommodation: "Accommodation Services",
      transportation: "Transportation Services",
      private_tours: "Private Tours",
      restaurants: "Restaurants",
  },
  ar: {
      home: "الرئيسية",
      about: "من نحن",
      services: "الخدمات",
      destinations: "الوجهات",
      reviews: "التقييمات",
      gallery: "المعرض",
      contact: "اتصل بنا",
      booking: "الحجز",
      login: "تسجيل الدخول",
      who_we_are: "من نحن",
      who_description: "في DiscoverJordan، نقدم تجارب سفر لا تُنسى تسلط الضوء على التاريخ العريق للأردن، والمناظر الخلابة، والضيافة الدافئة. من البتراء إلى البحر الميت، نضمن أن تكون كل رحلة مميزة.",
      vision: "رؤيتنا",
      vision_description: "أن نكون المنصة الرائدة للسفر في الأردن، ونوفر تجارب غامرة وأصيلة تربط المسافرين بثقافتنا المحلية.",
      mission: "مهمتنا",
      mission_description: "نصمم تجارب سفر مخصصة لجميع أنواع المسافرين، مع التركيز على الاستدامة، ودعم المجتمعات المحلية، وتوفير تجربة سفر سلسة.",
      why_choose: "لماذا تختار DiscoverJordan؟",
      why_description: "اختر DiscoverJordan للرحلات بإرشاد الخبراء، والوصول الحصري إلى الكنوز المخفية، والتجارب الثقافية الأصيلة. مع نظام الحجز السهل والآمن لدينا، ستكون رحلتك سلسة من البداية إلى النهاية.",
      footer: "© 2025 DiscoverJordan | جميع الحقوق محفوظة.",
      page_title_home: "احجز الان ",
      page_title_about: "من نحن ",
      full_name: "الاسم الكامل:",
      email: "البريد الإلكتروني:",
      phone: "رقم الهاتف:",
      full_name_placeholder: "أدخل اسمك",
      email_placeholder: "أدخل بريدك الإلكتروني",
      phone_placeholder: "أدخل رقم هاتفك",
      submit_booking: "إرسال الحجز",
      contact_title: "اتصل بنا",
      contact_description: "نود سماع رأيك. يرجى ملء النموذج أدناه للتواصل معنا.",
      name_label: "اسمك:",
      email_label: "بريدك الإلكتروني:",
      message_label: "رسالتك:",
      submit_button: "إرسال الرسالة",
      contact_title: "اتصل بنا",
      contact_description: "نود سماع رأيك! يرجى التواصل معنا لأي استفسارات أو ملاحظات.",
      get_in_touch: "تواصل معنا",
      full_name_placeholder: "أدخل اسمك",
      email_placeholder: "أدخل بريدك الإلكتروني",
      message_label: "رسالتك",
      submit_button: "إرسال الرسالة",
      our_address: "عنواننا",
      follow_us: "تابعنا",
      address: "عمان، الأردن",
      explore1:"Explore the Most Beautiful Destinations in Jordan",
      explore: "اكتشف أجمل الوجهات في الأردن مع خدماتنا السياحية الفريدة! نساعدك في تصميم رحلتك المثالية بكل سهولة.",
      discover: "اكتشف الأماكن المدهشة وخطط لمغامرتك القادمة!",
      topDestinations: "أهم الوجهات",
      petraDescription: "مدينة البتراء القديمة، واحدة من عجائب الدنيا السبع.",
      wadiRumDescription: "تجربة المناظر الصحراوية المدهشة والأنشطة المغامرة.",
      deadSeaDescription: "السباحة بسهولة في أكثر المياه ملوحة في العالم.",
      explore_now: "استكشف الوجهات الآن",
      request_services: "طلب خدماتنا",
      what_visitors_say: "ماذا يقول زوارنا",
      read_experiences: "اقرأ تجارب المسافرين الذين استكشفوا الأردن معنا.",
      review_1: '"تجربة رائعة! البتراء ووادي رم كانتا مذهلتين. أوصي بشدة!"',
      review_2: '"مرشدين رائعين، حجز سلس، ومغامرات لا تُنسى. شكرًا!"',
      review_3: '"أحببت الضيافة المحلية والمناظر الطبيعية الجميلة. سأزور مرة أخرى!"',
      leave_review: "اترك رايك",
      submit_review: "إرسال",
      services_title: "خدماتنا السياحية",
      services_intro: "اكتشف مجموعة واسعة من الخدمات التي نقدمها لرحلتك المثالية في الأردن.",
      tourist_tours: "الجولات السياحية",
      tourist_tours_desc: "اكتشف المعالم الرئيسية مثل البتراء، البحر الميت، وادي رم والمزيد.",
      historical_tours: "الجولات التاريخية والثقافية",
      historical_tours_desc: "استمتع بتاريخ الأردن العريق من خلال جولاتنا الثقافية.",
      accommodation: "خدمات الإقامة",
      accommodation_desc: "ابحث عن أفضل الفنادق أو الشقق القريبة من المعالم الرئيسية.",
      transportation: "خدمات النقل",
      transportation_desc: "استأجر سيارة أو احجز وسيلة نقل خاصة بين المعالم.",
      private_tours: "الجولات الخاصة",
      private_tours_desc: "جولات مخصصة وفقًا لاهتماماتك وتفضيلاتك.",
      restaurants: "المطاعم",
      restaurants_desc: "اكتشف أفضل أماكن تناول الطعام في الأردن، من الأطباق التقليدية إلى العالمية.",
      tourist_tours: "الجولات السياحية",
      historical_tours: "الجولات التاريخية والثقافية",
      accommodation: "خدمات الإقامة",
      transportation: "خدمات النقل",
      private_tours: "الجولات الخاصة",
      restaurants: "المطاعم",
  }
};

function switchLanguage(lang) {
  document.documentElement.setAttribute("lang", lang);
  
  const langTexts = document.querySelectorAll('.lang-text');
  langTexts.forEach((element) => {
    const key = element.getAttribute('data-lang');
    element.textContent = translations[lang][key] || element.textContent;
  });

  const serviceLabels = document.querySelectorAll('label[data-lang]');
  serviceLabels.forEach((label) => {
    const serviceKey = label.getAttribute('data-lang');
    label.textContent = translations[lang][serviceKey] || label.textContent;
  });
}
